### Testaus


### Get items
GET http://localhost:3000/api/items

### Get items id
GET http://localhost:3000/api/items/40

### post items
POST http://localhost:3000/api/items
Content-Type: application/json

{
    "name": "Vesimelooni"
}

### Update (PUT)
PUT http://localhost:3000/api/items/update/2
Content-Type: application/json

{
    "name": "Vesimelooni"
}
### Delete
DELETE http://localhost:3000/api/items/delete/1

### User tests
GET http://localhost:3000/api/users

### Get by id
GET http://localhost:3000/api/users/1

### POST user

POST http://localhost:3000/api/users
Content-Type: application/json

{
    "username" : "watermelon",
    "password" : "watermelon1",
    "email": "watermelon@melon.com"   
}
### PUT

PUT http://localhost:3000/api/users/update/1
Content-Type: application/json

{
    "username" : "watermelon",
    "password" : "watermelon1",
    "email": "watermelon@melon.com"    
}
### Delete

DELETE http://localhost:3000/api/users/delete/4